## Process this file with automake to produce Makefile.in

SUBDIRS = graphs linux.x86 regression_tests

EXTRA_DIST = \
	2757.dot \
	2758.dot \
	2760.dot \
	2764.dot \
	2781.dot \
	2814.dot \
	cl.py \
	concentrate_edge_identity_tooltip.c \
	concentrate_repeat_layout.c \
	concentrate_segment_weight.c \
	graphs \
	gvtest.py \
	nshare \
	routecert.c \
	test_rtest.py \
	tests.txt \
	test_regression.py
